// <auto-generated />
namespace SocialNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class overrideconventionsforgigandgenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(overrideconventionsforgigandgenre));
        
        string IMigrationMetadata.Id
        {
            get { return "202103030625571_overrideconventionsforgigandgenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
